---
.travis.yml:
  docker_sets:
    - set: debian8-64
    - set: debian9-64
    - set: debian10-64
    - set: ubuntu1604-64
    - set: ubuntu1804-64
    - set: centos6-64
    - set: centos7-64
  secure: "j/Db/NnuJUwyFWGVwZEciC/0Xrhaes647UK49ZnlZTjUppUeTsqY/rKE8Pc4jpiW8DsfeGijCYP1O02tquH+KSKSwiwxIBjbToFjhNNJ6Qgh0DGIR29VZkiyirh5ZkK1yLMx9Ciyn8opwOXHqTRMk6JwAY05Gux1sD2T7Eu2c4w="
spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml:
  delete: true
spec/acceptance/nodesets/ec2/image_templates.yaml:
  delete: true
spec/acceptance/nodesets/ec2/rhel-73-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml:
  delete: true
spec/acceptance/nodesets/archlinux-2-x64.yml:
  delete: true
